### PR TITLE
Changed types & interfaces usage & definition

### LINKED ISSUE #70: types needs to be optimized
**Describe the bug**
Currently types in project have following issues:

1. interface naming convention are not clean. Eg: FooterData can be just Footer
2. types and interfaces are spread across type file and component file. Interfaces if (are) reusable and should be in a separate file. types should be in the component. Basically one clear approach should be there

**To Reproduce**
1. Go to project code
3. Click on types

**Expected behavior**
A clear:
1. naming convention
2. rules around where to keep types and interfaces

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by greykoalacode**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #70 

**Snapshots/Videos:**

## Type of change

- [x] 🧑‍💻 Code Refactor

## Added tests?

- [ ] 👍 Yes
- [x] 🙅 No, because they aren't needed
- [ ] 🙋 No, because I need help

## Internationalization Support?

- [ ] 👍 Yes, Added text tokens
- [x] 🙅 No, because they aren't needed
- [ ] 🙋 No, because I need help

**Steps to test the feature:**

**Snapshot of the test-cases that are passing:**

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
I have tried to bring a format of writing types & interfaces as we discussed @Neha . Interfaces are only written if used at multiple places and types are written within a component. Naming has been improved from before and if you feel it can be better, let me know. Thanks for the opportunity :)

### CODE REVIEW

File: components/Cards/JobCard.tsx [hunk 1]
```diff
@@ -2,11 +2,25 @@ import React from "react";
...
-import { JobData } from "@/types";
 
-interface JobCardProps extends JobData {
+export type JobCardProps = Job & {
   className?: string;
 }
+
+type Job = {
+  id: number;
+  company_name: string;
```
Comment (Neha) [inline components/Cards/JobCard.tsx:12]: There should not be _. Use camelCase

File: components/Cards/JobCard.tsx [hunk 2]
```diff
@@ -2,11 +2,25 @@ import React from "react";
...
+  location: {
+    city: string;
+    country: string;
+  };
+  is_remote: boolean;
```
Comment (Neha) [inline components/Cards/JobCard.tsx:17]: There should not be _. Use camelCase

File: components/Cards/JobCard.tsx [hunk 3]
```diff
@@ -2,11 +2,25 @@ import React from "react";
...
+  experience: string;
+  role: string;
+  company_logo: string;
```
Comment (Neha) [inline components/Cards/JobCard.tsx:20]: Please replace _ with camelCase across all files.

**Review by Neha — CHANGES_REQUESTED** [review]
Thank you for your work. Apologies for the delay in review. I was traveling.

File: components/Cards/JobCard.tsx (hunk 1 above)
Comment (greykoalacode) [reply components/Cards/JobCard.tsx:12]: Sure, sorry about that, will make necessary changes and push them.

File: components/Cards/JobCard.tsx (hunk 3 above)
Comment (greykoalacode) [reply components/Cards/JobCard.tsx:20]: Should we replace _ with camelCase in files like DropDown , etc as well ? because there as well I could find props like filter_name, filter_options, filter_background

**Comment by greykoalacode** [comment]
Let me know if there's anything more to improve. Thank you! @Neha

File: components/Cards/JobCard.tsx (hunk 3 above)
Comment (Neha) [reply components/Cards/JobCard.tsx]: Yes, please
